language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
sudo: false
# run builds for both the nightly and beta branch
rust:
  - nightly
  - beta
  - 1.0.0

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo doc
after_success:
  - travis-cargo --only 1.0.0 doc-upload
  - travis-cargo coveralls --no-sudo

env:
  global:
    secure: "XlN/Vf8a+QuHky7RHRf3i4rR1dIegb1nSmTMqRVNzFDeeMVt1su/2ExdbwM0Fj/VZLj0VNOYu/SHcYXEMtUr/GVebonac+tcQveNNidx2ts/9anaERqlI2pP1gulyEzAljnPe4bG9SsqLTfKAiZblgEHl643F1X+/1zGGgyRD6I="
notifications:
    webhooks: http://huon.me:54856/travis
