language: rust
# run builds for both the nightly and beta branch
rust:
  - nightly
  - beta

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo doc
after_success:
  - travis-cargo --only beta doc-upload
  - travis-cargo coveralls

env:
  global:
    secure: "XlN/Vf8a+QuHky7RHRf3i4rR1dIegb1nSmTMqRVNzFDeeMVt1su/2ExdbwM0Fj/VZLj0VNOYu/SHcYXEMtUr/GVebonac+tcQveNNidx2ts/9anaERqlI2pP1gulyEzAljnPe4bG9SsqLTfKAiZblgEHl643F1X+/1zGGgyRD6I="
notifications:
    webhooks: http://huon.me:54856/travis
